//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Classes
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.IO;
    using TurkmenBuildProjectServer.Classes;

    public partial class Goods
    {
        public int Id { get; set; }
        public string GoodName { get; set; }
        public double Weight { get; set; }
        public double RentPrice { get; set; }
        public string Information { get; set; }
        public string Picture { get; set; }
    
        public virtual Rent Rent { get; set; }

        public Goods(string Name, double Weight, double Price, string Information, Rent rent)
        {
            this.GoodName = Name;
            this.Weight = Weight;
            this.RentPrice = Price;
            this.Information = Information;
            this.Rent = rent;
            this.Picture = @"\pictures\goods\default-good.jpg";
        }

        public Goods(string Name, double Weight, double Price, string Information, string Picture, Rent rent)
        {
            this.GoodName = Name;
            this.Weight = Weight;
            this.RentPrice = Price;
            this.Information = Information;
            this.Rent = rent;
            this.Picture = Picture;
        }

        public Goods() { }

        public string ToJson()
        {
            Image GoodPicture = Image.FromFile(this.Picture);
            byte[] GoodPictureArray = ByteConverter.ConvertToByteArray(GoodPicture);

            Dictionary<string, object> GoodDictionary = new Dictionary<string, object>()
            {
                { "Id", this.Id },
                { "GoodName", this.GoodName},
                { "Weight", this.Weight},
                { "RentPrice", this.RentPrice},
                { "Information", this.Information},
                { "Picture", Convert.ToBase64String(GoodPictureArray)},
            };
            return JsonConvert.SerializeObject(GoodDictionary);
        }
    }
}
