//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Classes
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime DateOfOrder { get; set; }
        public string OrderType { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Rent Rent { get; set; }
        public virtual Project Project { get; set; }

        public Order(int UserId, string OrderType, Rent rent)
        {
            this.UserId = UserId;
            this.OrderType = OrderType;
            this.DateOfOrder = DateTime.Now;
            this.Rent = rent;
        }

        public Order(int UserId, string OrderType, Project project)
        {
            this.UserId = UserId;
            this.OrderType = OrderType;
            this.DateOfOrder = DateTime.Now;
            this.Project = project;
        }

        public Order() { }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(new Dictionary<string, object>()
            {
                { "Id", this.Id },
                { "UserId", this.UserId },
                { "OrderType", this.OrderType },
                { "DateOfOrder", this.DateOfOrder },
                { "Rent", Rent != null ? this.Rent.ToJson() : null },
                { "Project", Project != null ? this.Project.ToJson() : null }
            });
        }
    }
}
