//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Classes
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Id { get; set; }
        public int DurationTime { get; set; }
        public string RentType { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Vehicles Vehicles { get; set; }

        public Rent(int DurationTime, string Type)
        {
            this.DurationTime = DurationTime;
            this.RentType = Type;
        }

        public Rent(string Type)
        {
            this.RentType = Type;
            this.DurationTime = 0;
        }

        public Rent() { }

        public string ToJson()
        {      
            return JsonConvert.SerializeObject(new Dictionary<string, object>()
            {
                { "Id", this.Id },
                { "DurationTime", this.DurationTime },
                { "RentType", this.RentType },
                { "Vehicles", this.Vehicles != null ? this.Vehicles.ToJson() : null },
                { "Goods", this.Goods != null ? this.Goods.ToJson() : null },
                { "Order", this.Order != null ? new Dictionary<string, object>() { { "Id", this.Order.Id } } : null}
            });            
        }
    }
}
