//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Classes
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.IO;
    using TurkmenBuildProjectServer.Classes;

    public partial class UserProfile
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Information { get; set; }
        public string Picture { get; set; }
    
        public virtual User User { get; set; }

        public UserProfile(string Username, string Email, string Phone, string Information, User user, string ProfilePicture)
        {
            this.Username = Username;
            this.Email = Email;
            this.Phone = Phone;
            this.Information = Information;
            this.Picture = ProfilePicture;
            this.User = user;
        }

        public UserProfile(string Username, string Email, string Phone, string Information, User user)
        {
            this.Username = Username;
            this.Email = Email;
            this.Phone = Phone;
            this.Information = Information;
            this.User = user;
            this.Picture = @"\pictures\users\Мужик-строитель.jpg";
        }
        public UserProfile() { }

        public Dictionary<string, object> ToJson()
        {
            Image ProfilePicture = Image.FromFile(Picture);
            byte[] ProfilePictureArray = ByteConverter.ConvertToByteArray(ProfilePicture);

            return new Dictionary<string, object>()
            {
                { "Username", this.Username},
                { "Phone", this.Phone},
                { "Email", this.Email },
                { "Information", this.Information},
                { "ProfilePicture", Convert.ToBase64String(ProfilePictureArray)},
                { "Id", this.Id }
            };
        }
    }
}
