//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.Classes
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User(string Login, string Password, string Role)
        {
            this.Order = new HashSet<Order>();
            this.Login = Login;
            this.Password = Password;
            this.Role = Role;
        }
        public User() { }

        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(new Dictionary<string, object>()
            {
                { "Id", this.Id },
                { "Login", this.Login},
                { "Role", this.Role},
                { "UserProfile", this.UserProfile.ToJson() }
            });
        }
    }
}
